# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

def fibonacci_even_sum(limit):
    sum = 0
    cur = 1
    pre = 0

    while cur <= limit:
        if cur % 2 == 0:
            sum += cur
        
        tmp = cur + pre
        pre = cur
        cur = tmp

    return sum

print(fibonacci_even_sum(4000000))